apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: php-server
  labels:
    name: php-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-server
  template:
    metadata:
      labels:
        app: php-server
    spec:
      containers:
        - name: php-server
          image: php:v1
          volumeMounts:
          - name: nginx-data
            mountPath: /usr/share/nginx/html
          ports:
          - containerPort: 9000
      volumes:
        - name: nginx-data
          hostPath:
            path: /var/www/html